# Copyright 2025 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is for use with the REST Client extension for Visual Studio Code to make it easy to manually 
# test the Test Service Web API.
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@hostname = localhost
@port = 63123
@repo_id = local_dev_repo
@test_id = building_comfort
@test_run_id = test_run_001
@query_id = room-comfort-level

### Homepage
GET http://{{hostname}}:{{port}}

### GET STATE of test run query
GET http://{{hostname}}:{{port}}/test_run_host/queries/{{repo_id}}.{{test_id}}.{{test_run_id}}.{{query_id}}

### GET RESULT PROFILE of test run query
GET http://{{hostname}}:{{port}}/test_run_host/queries/{{repo_id}}.{{test_id}}.{{test_run_id}}.{{query_id}}/profile

### START test run query
POST http://{{hostname}}:{{port}}/test_run_host/queries/{{repo_id}}.{{test_id}}.{{test_run_id}}.{{query_id}}/start
Content-Type: application/json

### PAUSE test run query
POST http://{{hostname}}:{{port}}/test_run_host/queries/{{repo_id}}.{{test_id}}.{{test_run_id}}.{{query_id}}/pause
Content-Type: application/json

### STOP test run query
POST http://{{hostname}}:{{port}}/test_run_host/queries/{{repo_id}}.{{test_id}}.{{test_run_id}}.{{query_id}}/stop
Content-Type: application/json

### RESET test run query
POST http://{{hostname}}:{{port}}/test_run_host/queries/{{repo_id}}.{{test_id}}.{{test_run_id}}.{{query_id}}/reset
Content-Type: application/json