# Copyright 2025 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ConfigMap for the service configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: drasi-test-config
  namespace: drasi-system
data:
  e2e_test_config.json: |
    {
      "data_store": {
        "test_repos": [
          {
              "id": "github_dev_repo",
              "kind": "GitHub",
              "owner": "drasi-project",
              "repo": "test-repo",
              "branch": "query-host",
              "force_cache_refresh": true,
              "root_path": "dev_repo"
          }
        ]
      },
      "test_run_host": {
        "test_runs": [
          {
            "test_id": "building_comfort_small",
            "test_repo_id": "github_dev_repo",
            "test_run_id": "test_run_001",
            "sources": [
              {
                "test_source_id": "facilities-db",
                "start_mode": "bootstrap",
                "test_run_overrides": {
                  "model_data_generator": {
                    "spacing_mode": "none",
                    "time_mode": "live"
                  },
                  "source_change_dispatchers": [
                    {
                      "kind": "RedisStream",
                      "host": "drasi-redis",
                      "port": 6379
                    }
                  ]
                }
              }          
            ],
            "queries": [
              {
                "test_query_id": "room-comfort-level",
                "start_immediately": true,
                "test_run_overrides" : {
                  "stop_trigger": {
                    "kind": "RecordCount",
                    "record_count": 91250
                  }
                },
                "loggers": [
                  {
                    "kind": "Profiler",
                    "write_bootstrap_log": false,
                    "write_change_image": true,
                    "write_change_log": false,
                    "write_change_rates": true,
                    "write_distributions": true
                  }
                ]
              }          
            ]
          }
        ]
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drasi-test-service
  namespace: drasi-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasi-test-service
  template:
    metadata:
      labels:
        app: drasi-test-service
      annotations:
          dapr.io/app-id: drasi-test-service
          dapr.io/config: dapr-config
          dapr.io/enabled: "true"
          dapr.io/sidecar-image: daprio/daprd
    spec:
      containers:
      - name: drasi-test-service
        image: drasi-project/e2e-test-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 63123
        env:
        - name: RUST_LOG
          value: "debug"
        - name: DRASI_CONFIG_FILE
          value: "/etc/drasi/e2e_test_config.json"        
        volumeMounts:
        - name: config-volume
          mountPath: /etc/drasi      
      volumes:
      - name: config-volume
        configMap:
          name: drasi-test-config    
---
apiVersion: v1
kind: Service
metadata:
  name: drasi-test-service
  namespace: drasi-system  
spec:
  selector:
    app: drasi-test-service
  ports:
    - protocol: TCP
      port: 63123
      targetPort: 63123
  type: NodePort
