# Copyright 2025 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is for use with the REST Client extension for Visual Studio Code to make it easy to manually 
# test the Test Service Web API.
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@hostname = localhost
@port = 63123
@repo_id = github_dev_repo
@test_id = building_comfort
@test_run_id = test_run_001
@source_id = facilities-db
@fq_test_run_id = {{repo_id}}.{{test_id}}.{{test_run_id}}

### Homepage
GET http://{{hostname}}:{{port}}


# DOCS
### API Docs
GET http://{{hostname}}:{{port}}/docs

### OpenAPI Spec 
GET http://{{hostname}}:{{port}}/api-docs/openapi.json


# TEST REPOS
### GET LIST of Test Repos
GET http://{{hostname}}:{{port}}/api/test_repos

### GET DETAIL of specific Test Repo
GET http://{{hostname}}:{{port}}/api/test_repos/{{repo_id}}

### GET LIST of Tests in specific Test Repo
GET http://{{hostname}}:{{port}}/api/test_repos/{{repo_id}}/tests

TODO - this does not work: empty list even though test is accessible directly

### GET DETAIL of specific Test
GET http://{{hostname}}:{{port}}/api/test_repos/{{repo_id}}/tests/{{test_id}}

### GET LIST of Sources for specific Test
GET http://{{hostname}}:{{port}}/api/test_repos/{{repo_id}}/tests/{{test_id}}/sources

TODO - this does not work - 500 Internal Server Error

### GET DETAIL of specific Source for specific Test
GET http://{{hostname}}:{{port}}/api/test_repos/{{repo_id}}/tests/{{test_id}}/sources/{{source_id}}

# TEST RUNS
### GET LIST of Test Runs
GET http://{{hostname}}:{{port}}/api/test_runs

### GET DETAIL of a specific Test Run
GET http://{{hostname}}:{{port}}/api/test_runs/{{fq_test_run_id}}

### Start a specific Test Run
POST http://{{hostname}}:{{port}}/api/test_runs/{{fq_test_run_id}}/start

TODO - this does not work, it seems to hang Test Service

### Stop a specific Test Run
POST http://{{hostname}}:{{port}}/api/test_runs/{{fq_test_run_id}}/stop

TODO - this does not work, it seems to hang Test Service
